### ISSUE TITLE
Import Error Captcha Parser

### ISSUE THREAD

**Issue by rahulkapoor90** [kishore-narendran/FacultyInformationScraper#4]
I get this " ImportError: No module named CaptchaParser " while trying your repository where to get captchaparser please mention it in requirements.txt

**Comment by kishore-narendran** [comment]
You can get that from here, https://github.com/karthikb351/CaptchaParser/blob/master/CaptchaParser.py.

However since it isn't like a Python library with a setup.py and all I can't set up the git repo in the requirements.txt. Also, the scraper is currently non-functional because of some page changes. 

-----Original Message-----

**Comment by kishore-narendran** [comment]
@rahulkapoor90 : The scraper now works fine. The HTML formatting had changed, hence a bug in the scraping.

**Comment by rahulkapoor90** [comment]
Traceback (most recent call last):
  File "C:/Users/rahul/PycharmProjects/untitled/hrllo.py", line 107, in <module>
    aggregate()
  File "C:/Users/rahul/PycharmProjects/untitled/hrllo.py", line 88, in aggregate
    br = login()
  File "C:/Users/rahul/PycharmProjects/untitled/hrllo.py", line 32, in login
    br.form['regno'] = REGNO
  File "C:\Python27\lib\site-packages\mechanize\_form.py", line 2782, in __setitem__
    control.value = value
  File "C:\Python27\lib\site-packages\mechanize\_form.py", line 1217, in __setattr__
    raise TypeError("must assign a string")
TypeError: must assign a string

Why this error comes.

**Comment by kishore-narendran** [comment]
You need to enter your register number and password for login while running the python script.
`python hrllo.py <YOUR REGNO> <YOUR PASSWORD>`

**Comment by rahulkapoor90** [comment]
oh, there was problem with pycharm, thanks by the way.

**Comment by kishore-narendran** [comment]
Cool.
