### ISSUE TITLE
change of url

### ISSUE THREAD

**Issue by sair770** [kishore-narendran/FacultyInformationScraper#6]

**Comment by kishore-narendran** [comment]
@sair770 could you be a little more descriptive? 
I am no longer a student at VIT University. I am assuming you mean that the URL of the faculty information is now no longer the same? It would really helpful if you give me the new URL, or submit a PR which changes the URL in the source code.

**Comment by sair770** [comment]
The url has changed from academics.vit.ac.in to vtop.vit.ac.in

**Comment by kishore-narendran** [comment]
@sair770 Hey, I have changed the URLs in https://github.com/kishore-narendran/FacultyInformationScraper/commit/27b0603a51f2d1a21d82c605cdf2544b53c7afb8. I don't have a valid login anymore, if you can try this and tell me if it works, I'd appreciate it! 😄
